export const DB_NAME = "CC";
export const DATE_FORMAT_COMPARE = "YYYY-MM-DD";

export const ACTIONS = {
  YEARS_LIST: "YEARS_LIST",
  YEAR_SELECTED: "YEAR_SELECTED",
  ADD_RECORD: "ADD_RECORD",
  YEAR_UPDATE: "YEAR_UPDATE",
  DATE_UPDATE: "DATE_UPDATE",
  RECORD_UPDATE: "RECORD_UPDATE",
  RECORD_DELETE: "RECORD_DELETE",
  GET_TITLES: "GET_TITLES",
  GET_TITLES_RECORDS: "GET_TITLES_RECORDS"
}
